[project]
name = "mezcal"
description = "Mezzanine Caching and Access Layer Web Application"
version = "1.2.3"
dependencies = [
    "boto3",
    "click",
    "codetiming",
    "filelock",
    "flask",
    "pillow~=11.0",
    "python-dotenv",
    "requests",
    "requests-jwtauth",
    "waitress",
]

[project.optional-dependencies]
test = [
    "moto[s3]",
    "pycodestyle",
    "pytest",
    "pytest-cov",
    "pytest-datadir",
]

[project.scripts]
mezcal = "mezcal.server:run"
